GET http://localhost:3000/investors


###


GET http://localhost:3000/investors/66ad54241a03126ee8a6165c


###
POST http://localhost:3000/investors
Content-Type: application/json

{
    "name": "Person",
    "investingToCompany": "Lockheed Martin "
}

###
DELETE http://localhost:3000/investors/66ad4ed2e5e84c0ac343df72